### ISSUE TITLE
Optional dependencies not supported

### ISSUE THREAD

**Issue by jtojnar** [slince/di#7]
I have a class with an optional dependency on `CacheInterface` but currently, the container will try to resolve it in tests, even when it is not registered there and default value exists.

See the following simplified reproduction example:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

interface FooInterface { }

class Foo implements FooInterface { }

class Bar {
    public function __construct(?FooInterface $foo = null) { }
}

$container = new Slince\Di\Container();

// $container->register(FooInterface::class, Foo::class);

$bar = $container->get(Bar::class);
```

It fails with:

```
Fatal error: Uncaught Slince\Di\Exception\NotFoundException: There is no definition named "FooInterface" in /home/jtojnar/Projects/selfoss/vendor/slince/di/Container.php:257
Stack trace:
#0 /home/jtojnar/Projects/selfoss/vendor/slince/di/Container.php(221): Slince\Di\Container->resolveInstance('FooInterface')
#1 /home/jtojnar/Projects/selfoss/vendor/slince/di/Resolver.php(177): Slince\Di\Container->get('FooInterface')
#2 /home/jtojnar/Projects/selfoss/vendor/slince/di/Resolver.php(100): Slince\Di\Resolver->resolveDependencies(Array, Array)
#3 /home/jtojnar/Projects/selfoss/vendor/slince/di/Resolver.php(50): Slince\Di\Resolver->createFromClass(Object(Slince\Di\Definition))
#4 /home/jtojnar/Projects/selfoss/vendor/slince/di/Container.php(261): Slince\Di\Resolver->resolve(Object(Slince\Di\Definition))
#5 /home/jtojnar/Projects/selfoss/vendor/slince/di/Container.php(221): Slince\Di\Container->resolveInstance('Bar')
#6 /home/jtojnar/Projects/selfoss/slince.php(17): Slince\Di\Container->get('Bar')
#7 {main}
  thrown in /home/jtojnar/Projects/selfoss/vendor/slince/di/Container.php on line 257
```

**Comment by slince** [comment]
tks, fixed in 3.2.2
