### ISSUE TITLE
Cannot set scalar arguments after dependencies

### ISSUE THREAD

**Issue by jtojnar** [slince/di#8]
The following fails:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

class Foo { }

class Bar {
    public function __construct(Foo $foo, string $directory) { }
}

$container = new Slince\Di\Container();

$container->register(Bar::class)->addArgument(__DIR__ . '/temp');

$bar = $container->get(Bar::class);
```

```
Fatal error: Uncaught Slince\Di\Exception\DependencyInjectionException: Unresolvable dependency resolving "directory" in class "Bar" in /home/jtojnar/Projects/selfoss/vendor/slince/di/Resolver.php:189
Stack trace:
#0 /home/jtojnar/Projects/selfoss/vendor/slince/di/Resolver.php(100): Slince\Di\Resolver->resolveDependencies(Array, Array)
#1 /home/jtojnar/Projects/selfoss/vendor/slince/di/Resolver.php(50): Slince\Di\Resolver->createFromClass(Object(Slince\Di\Definition))
#2 /home/jtojnar/Projects/selfoss/vendor/slince/di/Container.php(261): Slince\Di\Resolver->resolve(Object(Slince\Di\Definition))
#3 /home/jtojnar/Projects/selfoss/vendor/slince/di/Container.php(221): Slince\Di\Container->resolveInstance('Bar')
#4 /home/jtojnar/Projects/selfoss/slince.php(15): Slince\Di\Container->get('Bar')
#5 {main}
  thrown in /home/jtojnar/Projects/selfoss/vendor/slince/di/Resolver.php on line 189
```

**Comment by slince** [comment]
hello, you can try like this

```php

$container->register(Bar::class)->setArgument(1, __DIR__ . '/temp');
// or
$container->register(Bar2::class)->setArgument('directory', __DIR__ . '/temp');


```

**Comment by jtojnar** [comment]
Thanks. That appears to work, even with `setArguments()`.
